### ISSUE TITLE
Follower feature is generally broken in frontend

### ISSUE THREAD

**Issue by gustavclausen** [DevOps-Drengene/DevOps-Project#51]
Identified issues:
- Follower status is not set to “following” after vistiting the profile a second time. Thus unfollow is not possible.

**Comment by casparolesen** [comment]
It's an issue with the direction of the follow relation between two users (in the DB).

So, either this (which gives the opposite result)
```
let following = false;
    if (currentUserId) {
      const followingRes = await profileUser.getFollow({ where: { id: currentUserId } });
      following = !!(followingRes.length);
    }
```
can be changed to this
```
let following = false;
    if (currentUserId) {
      const currentUser = await db.user.findOne({ where: { id: currentUserId } });
      const followingRes = await currentUser.getFollow({ where: { id: profileUser.id } });
      following = !!(followingRes.length);
    }
```

or the direction of the relation is to be reversed (which I have no clue how to do). Up to you @LasseRaatz
